### ISSUE TITLE
Add a command for evaluation

### ISSUE THREAD

**Issue by starride-teklia** [jpuigcerver/PyLaia#72]
I would like to create a new command `pylaia-htr-evaluate` to compute CER/WER. 

* Command:
```bash
pylaia-htr-evaluate --config evaluation_config.yaml
```
* Configuration file:
```yaml
eval:
   labels:
      train: path/to/train_labels.txt
      val: path/to/val_labels.txt
      test: path/to/test_labels.txt
   predictions:
      train: path/to/train_predictions.txt
      val: path/to/val_predictions.txt
      test: path/to/test_predictions.txt
```
* Output formatted in markdown: 

| Set  | CER (%)    | WER (%)   |
| ----- | ---------- | --------- | 
| train | 2.40       | 8.10      |
| val   | 7.45       | 19.75     |
| test  | 6.55       | 18.2      |
